version: '3'

services:
  app:
    build: .
    container_name: spark-stacker
    restart: unless-stopped
    ports:
      - "${WEBHOOK_PORT:-8080}:8080"
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    command: python app/main.py --config /app/config/config.json