global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          env: 'prod'

  - job_name: 'spark-stacker'
    metrics_path: /metrics
    static_configs:
      - targets: ['mock-metrics:8000']
        labels:
          app: 'spark-stacker'
          environment: 'development'

  # Add a mock job for the application metrics until they're implemented
  - job_name: 'spark-stacker-mock'
    metrics_path: /metrics
    static_configs:
      - targets: ['prometheus:9090']
        labels:
          app: 'spark-stacker-mock'
          environment: 'development'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'up'
        target_label: __name__
        replacement: spark_stacker_uptime_seconds
      - source_labels: [__name__]
        regex: 'process_cpu_seconds_total'
        target_label: __name__
        replacement: spark_stacker_trades_total
      - source_labels: [__name__]
        regex: 'prometheus_engine_query_duration_seconds'
        target_label: __name__
        replacement: spark_stacker_api_latency_seconds
