global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          env: 'prod'

  - job_name: 'spark-stacker'
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['spark-stacker:9000']
        labels:
          app: 'spark-stacker'
          environment: 'production'

  # Log metrics exporter job
  - job_name: 'log-metrics'
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['log-metrics:9001']
        labels:
          app: 'spark-stacker-logs'
          environment: 'production'

  # Loki metrics
  - job_name: 'loki'
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['loki:3100']
        labels:
          app: 'loki'
          environment: 'production'

  # Promtail metrics
  - job_name: 'promtail'
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['promtail:9080']
        labels:
          app: 'promtail'
          environment: 'production'

  # Removed mock metrics - using real metrics from spark-stacker container
