server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: spark-stacker
    static_configs:
      - targets:
          - localhost
        labels:
          job: spark-stacker
          app: spark-stacker
          __path__: /logs/*/spark_stacker.log
      - targets:
          - localhost
        labels:
          job: spark-stacker
          app: spark-stacker
          __path__: /logs/*.log
    pipeline_stages:
      - regex:
          expression: '(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}) - (?P<logger>[\w\.]+) - (?P<level>\w+) - (?P<message>.*)'
      - labels:
          level:
          logger:

  - job_name: connector-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: spark-stacker
          app: spark-stacker
          log_type: connector
          __path__: /logs/*/*/markets.log
      - targets:
          - localhost
        labels:
          job: spark-stacker
          app: spark-stacker
          log_type: connector
          __path__: /logs/*/*/balance.log
      - targets:
          - localhost
        labels:
          job: spark-stacker
          app: spark-stacker
          log_type: connector
          __path__: /logs/*/*/orders.log
    pipeline_stages:
      - regex:
          expression: '(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}) - (?P<connector>[\w\.]+) - (?P<level>\w+) - (?P<message>.*)'
      - labels:
          level:
          connector:
