server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/*log

  - job_name: spark-stacker-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: spark-stacker
          __path__: /logs/*.log

  - job_name: spark-stacker-json-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: spark-stacker-json
          __path__: /logs/*.json
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            category: category
            trace_id: trace_id
            data: data
      - labels:
          level:
          category:
          trace_id:
      - timestamp:
          source: timestamp
          format: RFC3339Nano
