version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: spark-stacker
    restart: unless-stopped
    ports:
      - "${WEBHOOK_PORT:-8080}:8080"
      - "9000:9000"
    volumes:
      - ../logs:/app/logs
      - ../../shared/config.json:/app/config.json
      - ../data:/app/data
    env_file:
      - ../../shared/.env
    environment:
      - PYTHONUNBUFFERED=1
      - CONFIG_FILE=/app/config.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    command: python app/main.py --config /app/config.json
    networks:
      - default
      - monitoring_network

networks:
  default:
    driver: bridge
  monitoring_network:
    external: true
    name: docker_monitoring
